config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :employees do
      collection do
        get 'forget_password'
        post 'forget_password'
        get 'reset_mail'
        get 'error_mail'
      end
    end
  end

  resources :attachments do
  end

  root to: 'desboard#index'
  devise_for :employees, path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' }, controllers: { sessions: "admin/sessions", passwords: "admin/passwords"}

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user = user || User.new
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    cannot :manage, :all
    #send("setup_#{@user.role.name}_access") if @user.present?
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachment_entity, polymorphic: true
  mount_uploader :path,  AttachmentUploader
  before_create :set_fields

  def set_fields
    self.content_type = path.content_type
	  self.file_size = path.size
	  self.name = path.get_original_filename
  end

  def attachment_path
    path.url
  end

end

app/models/employee.rb
class Employee < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable#, :trackable, :validatable

  has_many :attachments, as: :attachment_entity       

end

app/models/role.rb
class Role < ApplicationRecord

end

app/models/search_params.rb
class SearchParams
  extend ActiveModel::Naming
  def initialize(attributes = {})
    @attributes = (attributes || {}).stringify_keys.each{|k,v| v.to_s.strip! }
  end

  def attributes(controller = nil,focus = [])
    return @attributes if controller.blank?
    focus_attributes = focus.inject({}) {|h,i| h[i] = true; h}
    focus_attributes.merge(@attributes).inject({}){|h,i|
      m = "search_filter_#{i[0]}".downcase.strip.gsub(/[^_a-z0-9]+/,'_')
      if controller.respond_to?(m,true)
        if controller.method(m).arity == 1
          h[i[0]] = controller.send(m,i[1]) 
        else
          h[i[0]] = controller.send(m) 
        end
      else
        h[i[0]] = i[1]
      end
      h}
  end
  def params(controller = nil)
    attributes(controller)
  end

  def method_missing(method, *value)
    if method.to_s =~ /=$/
      @attributes[method.to_s.sub('=','').strip] = value
    else
      value = @attributes[method.to_s.strip]
    end
    value
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base
    protect_from_forgery with: :exception
    layout false 
    respond_to :html
    before_action :authenticate_employee!
end

app/controllers/admin/passwords_controller.rb
class Admin::PasswordsController < Devise::PasswordsController
  skip_before_action :require_no_authentication, :only => [:edit, :update]
  layout false 

  def edit
     super
  end

  # PUT /resource/password
  def update
    # super
  self.resource = resource_class.reset_password_by_token(resource_params)
  yield resource if block_given?
    if resource.errors.empty?
      resource.unlock_access! if unlockable?(resource)
      resource.employee_status = 'active'
      flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
      set_flash_message(:notice, flash_message) if is_flashing_format?
      sign_in(resource_name, resource)
      respond_with resource, location: after_resetting_password_path_for(resource)
    else
      respond_with resource
    end

  end
  
  protected

  def require_no_authentication
      if current_employee && current_employee.is?("admin")
          return true
      else
          return super
      end
  end
  
  def assert_reset_token_passed
    if params[:reset_password_token].blank?
        set_flash_message(:error, :no_token)
        redirect_to new_session_path(resource_name)
    end
  
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
 layout false  
 # before_action :configure_sign_in_params, only: [:create]
  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    resource = warden.authenticate!(scope: resource_name, recall: "#{controller_path}#new")
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)
    # resource.ensure_private_token!
    respond_to do |format|
      #format.html { redirect_to after_sign_in_path_for(resource) }
      #current_employee.add_log("#{current_employee.email} Login At #{Time.now.format_date(:full)}",request.ip)
      format.html { redirect_to login_jump_url }
      format.json { render status: '201', json: resource.as_json(only: [:login, :email, :private_token]) }
    end
  end

  # DELETE /resource/sign_out
  def destroy
    Rails.cache.delete("current_employee_#{current_employee.id}".to_sym)
    sign_out
    redirect_to temporary_reports_path
    #super
  end

  # 登录后不同角色跳转
  def login_jump_url
   temporary_reports_path
  end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_employee!
  
end

app/controllers/attachments_controller.rb
 class AttachmentsController < ApplicationController
  before_action :set_attachment

  def new
    
  end

  def create
    ActiveRecord::Base.transaction do 
      @entity.attachments.create(permitted_attachment)
      @entity.save_audits(operator_type: 'User', operator_id: current_user.id, note: @tag )
    end
    render :new
  end

  def destroy
    ActiveRecord::Base.transaction do 
      attachment = Attachment.find(params[:id])
      attachment.delete
      @entity.save_audits(operator_type: 'User', operator_id: current_user.id, note: @tag )
    end
    render :new
  end

  private

  def set_attachment
    @entity = params[:entity].constantize.find(params[:entity_id])
    @tag = params[:tag]
  end

  def permitted_attachment
    params.require(:attachment).permit(:path,:tag)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/attachments/_new.html.erb
<i class="close icon"></i>
<h2 class="ui dividing header"><%= params[:entity] %> <%= @tag %> Attachemnt</h2>
<div class=" ui content">
  <div class="ui three cards">
    <%@entity.attachments.each do |att| %>
      <div class='ui card uploaded_attachment'>
        <div class="ui content" id="attachment_<%= att.id %>">
          <div class="item">
            <%= link_to att.path.url, target: '_blank',class: 'ui image label' do%> 
              <i class="file icon blue"></i><%= att.name%>
            <%end%>
          </div>
        </div>
        <div class="extra content">
          <%= link_to 'Delete', attachment_path(att,entity: @entity.class.name, entity_id: @entity.id, tag: @tag), remote: true, method: :delete, class: 'ui button mini' %>
        </div>
      </div>
    <%end%>

    <div class='ui card new_attachment'>
      <div class="content">
        <%= form_for @entity.attachments.new, url: attachments_path(entity: @entity.class.name, entity_id: @entity.id, tag: @tag), remote: true, method: :post do |f| %>
          <div class=" two fields">
            <%= f.file_field :path, label: 'please select #{@tag} Attachemnt' %>
            <%= f.hidden_field :tag,:value=>@tag %>
          </div>
          <div class="actions ">
            <%= f.submit 'Upload', class: 'ui button primary mini' %>
          </div>
        <% end %>
      </div>
    
    </div>
  </div>  
</div>
<div class="actions ">
  <div class="ui cancel button">Cancel</div>
</div>

app/views/attachments/new.js.erb
$('#new_attachment_modal_<%= @entity.id %>').modal('setting', {autofocus: false}).modal('hide');
$('#new_attachment_modal_<%= @entity.id %>').remove();
$('body').append('<div class="ui modal" id="new_attachment_modal_<%= @entity.id %>"><%= j(render 'new') %></div>');
$('#new_attachment_modal_<%= @entity.id %>').modal('setting', {autofocus: false}).modal('show');

$('.dropdown').dropdown();
$(".button").popup();
$(".icon").popup();
$(".popups").popup();
$('.button.dropdown').dropdown({on: 'hover', action: function(text, value) {}});
$("#new_attachment").form({
  inline : true,
  fields: {
    path: {
      identifier: 'attachment[path]',
      rules: [{
        type: 'empty',
        prompt: 'please select <%=@tag%> Attachemnt'
      }]
    }
  }
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type'>
    <title>Pre-report</title>
    <%= stylesheet_link_tag 'admin/application' %>
    <%= javascript_include_tag 'admin/application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'shared/admin/top_bar' %>
    <div class="pusher">
      <div class="ui fluid container" >
        <div class="ui two column grid">

          <div class="side menu close_menu" id="sideMenu">
            <%= render 'shared/admin/sidebar' %>
          </div>

          <div class="sixteen wide column" id="content">
            <div class="thirteen wide column">
              <%= render 'shared/alert' %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= yield :scripts %>
  </body>
</html>

app/views/shared/admin/_sidebar.html.erb
<div class="ui vertical fluid menu" id="verticalMenu">
  <ul>
    <li>
      <a class="item">
        <i class="bar chart icon"></i>
        <span class="main_menu">告警管理</span>
        <i class="right dropdown icon"></i>
      </a>
      <div class="menu content child active">
        <%#= link_to temporary_reports_path, class: 'item', active_class: 'actives' do %>
         <!--  <i class="left bullseye icon"></i>
          <span>监控页面</span> -->
        <%# end %>
      </div>
    </li>
  </ul>
</div>

app/views/shared/admin/_top_bar.html.erb
<div class="ui fixed top menu">
  <a href="javascript:void(0)" class="icon active item" id="hideToggle" style="display: flex;"><h3><i class="content icon"></i></h3></a>
  <a href="javascript:void(0)" class="icon active item" id="showToggle" style="display: none;"><h3><i class="content icon"></i></h3></a>
  <a href="/admin" data-toggle="slide" class="item"><h3>Pre-report</h3></a>
  <div class="right menu ">
    <!-- 头像 -->
    <div class="item"><span><%= current_employee&.name %></span></div>
    <a class="icon item pointer" data-toggle="popup" data-content="#user" data-position="bottom right">
      <%= image_tag 'male.jpg', class: 'ui avatar image' %>
    </a>
    <div id="user" class="ui popup">
      <div class="ui secondary vertical menu">
        <%= link_to destroy_employee_session_path, method: 'delete', class: 'item' do %>
          退出系统 <i class="sign out icon"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>